download_url: https://galaxy.ansible.com/download/ansible-netcommon-4.1.0.tar.gz
format_version: 1.0.0
name: netcommon
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 4.1.0
version_url: https://galaxy.ansible.com/api/v2/collections/ansible/netcommon/versions/4.1.0/
