---
all:
  children:
    EOS_DESIGNS_UNIT_TESTS:
      children:
        CLEAN_UNIT_TESTS:
          hosts:
            cvp-instance-ips-cvaas:
            device.with.dots.in.hostname:
            filter.only_vlans_in_use:
        CORE_UNIT_TESTS:
          hosts:
            core-1-isis-sr-ldp:
            core-2-ospf-ldp:
        TRUNK_GROUP_TESTS:
          children:
            TRUNK_GROUP_TESTS_L3LEAF:
              hosts:
                trunk-group-tests-l3leaf1a:
                trunk-group-tests-l3leaf1b:
                trunk-group-tests-l3leaf2a:
                trunk-group-tests-l3leaf2b:
            TRUNK_GROUP_TESTS_L2LEAF:
              hosts:
                trunk-group-tests-l2leaf1a:
                trunk-group-tests-l2leaf1b:
                trunk-group-tests-l2leaf3:
                trunk-group-tests-l2leaf4:
        NETWORK_PORTS_TESTS:
          hosts:
            network-ports-tests.1:
            network-ports-tests-2:
        UPLINK_MLAG_STRUCTURED_CONFIG_TESTS:
          children:
            UPLINK_MLAG_STRUCTURED_CONFIG_SPINES:
              hosts:
                UPLINK-MLAG-STRUCTURED-CONFIG-SPINE1:
            UPLINK_MLAG_STRUCTURED_CONFIG_L3LEAFS:
              hosts:
                UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1A:
                UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B:
            UPLINK_MLAG_STRUCTURED_CONFIG_L2LEAFS:
              hosts:
                UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1A:
                UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B:
        UNDERLAY_MULTICAST_TESTS:
          children:
            UNDERLAY_MULTICAST_SPINES:
              hosts:
                UNDERLAY-MULTICAST-SPINE1:
                UNDERLAY-MULTICAST-SPINE2:
            UNDERLAY_MULTICAST_L3LEAFS:
              hosts:
                UNDERLAY-MULTICAST-L3LEAF1A:
                UNDERLAY-MULTICAST-L3LEAF1B:
                UNDERLAY-MULTICAST-L3LEAF2A:
                UNDERLAY-MULTICAST-L3LEAF2B:
            UNDERLAY_MULTICAST_L2LEAFS:
              hosts:
                UNDERLAY-MULTICAST-L2LEAF1A:
        IGMP_QUERIER_TESTS:
          children:
            IGMP_QUERIER_L3LEAFS:
              hosts:
                IGMP-QUERIER-L3LEAF1A:
            IGMP_QUERIER_L2LEAFS:
              hosts:
                IGMP-QUERIER-L2LEAF1A:
        BGP_PEER_GROUPS_STRUCTURED_CONFIG:
          hosts:
            bgp-peer-groups-structured-config-1:
            bgp-peer-groups-structured-config-2:
        EVPN_MULTICAST_TESTS:
          children:
            EVPN_MULTICAST_TESTS_SPINES:
              hosts:
                EVPN-MULTICAST-SPINE1:
            EVPN_MULTICAST_TESTS_L3LEAFS:
              children:
                EVPN_MULTICAST_L3LEAF1:
                  hosts:
                    EVPN-MULTICAST-L3LEAF1A:
                    EVPN-MULTICAST-L3LEAF1B:
                EVPN_MULTICAST_L3LEAF2:
                  hosts:
                    EVPN-MULTICAST-L3LEAF2A:
            EVPN_MULTICAST_TESTS_L2LEAFS:
              hosts:
                EVPN-MULTICAST-L2LEAF1A:
        SVI_PROFILE_TESTS:
          hosts:
            SVI_PROFILE_NODE_1:
            SVI_PROFILE_NODE_2:
        RD_RT_ADMIN_SUBFIELD_TESTS:
          hosts:
            RD-RT-ADMIN-SUBFIELD-L3LEAF1:
            RD-RT-ADMIN-SUBFIELD-L3LEAF2:
            RD-RT-ADMIN-SUBFIELD-L3LEAF3:
            RD-RT-ADMIN-SUBFIELD-L3LEAF4:
            RD-RT-ADMIN-SUBFIELD-L3LEAF5:
            RD-RT-ADMIN-SUBFIELD-L3LEAF6:
            RD-RT-ADMIN-SUBFIELD-L3LEAF7:
        CUSTOM_TEMPLATES_TESTS:
          children:
            CUSTOM_TEMPLATES_SPINES:
              hosts:
                CUSTOM-TEMPLATES-SPINE1:
            CUSTOM_TEMPLATES_L3LEAFS:
              hosts:
                CUSTOM-TEMPLATES-L3LEAF1A:
                CUSTOM-TEMPLATES-L3LEAF1B:
        AVD_LAB:
          children:
            DC1_FABRIC:
              children:
                DC1_SPINES:
                  hosts:
                    DC1-SPINE1:
                      ansible_host: 192.168.200.101
                    DC1-SPINE2:
                      ansible_host: 192.168.200.102
                    DC1-SPINE3:
                      ansible_host: 192.168.200.103
                    DC1-SPINE4:
                      ansible_host: 192.168.200.104
                DC1_LEAFS:
                  children:
                    DC1_LEAF1:
                      hosts:
                        DC1-LEAF1A:
                          ansible_host: 192.168.200.105
                    DC1_LEAF2:
                      hosts:
                        DC1-LEAF2A:
                          ansible_host: 192.168.200.106
                        DC1-LEAF2B:
                          ansible_host: 192.168.200.107
                    DC1_SVC3:
                      hosts:
                        DC1-SVC3A:
                          ansible_host: 192.168.200.108
                        DC1-SVC3B:
                          ansible_host: 192.168.200.109
                    DC1_BL1:
                      hosts:
                        DC1-BL1A:
                          ansible_host: 192.168.200.110
                        DC1-BL1B:
                          ansible_host: 192.168.200.111
                    DC1_BL2:
                      hosts:
                        DC1-BL2A:
                          ansible_host: 192.168.200.117
                        DC1-BL2B:
                          ansible_host: 192.168.200.118
                    DC1_CL1:
                      hosts:
                        DC1-CL1A:
                          ansible_host: 192.168.200.119
                        DC1-CL1B:
                          ansible_host: 192.168.200.120
                    UNIT_TESTS:
                      hosts:
                        evpn_services_l2_only_true:
                        evpn_services_l2_only_false:
                    DC1_UNDEPLOYED_LEAF1:
                      hosts:
                        DC1_UNDEPLOYED_LEAF1A:
                          is_deployed: false
                          ansible_host: 192.168.200.121
                        DC1_UNDEPLOYED_LEAF1B:
                          is_deployed: false
                          ansible_host: 192.168.200.122
                DC1_L2LEAFS:
                  children:
                    DC1_L2LEAF1:
                      hosts:
                        DC1-L2LEAF1A:
                          ansible_host: 192.168.200.112
                        DC1-L2LEAF1B:
                          ansible_host: 192.168.200.115
                    DC1_L2LEAF2:
                      hosts:
                        DC1-L2LEAF2A:
                          ansible_host: 192.168.200.113
                        DC1-L2LEAF2B:
                          ansible_host: 192.168.200.114
                    DC1_L2LEAF3:
                      hosts:
                        DC1-L2LEAF3A:
                          ansible_host: 192.168.200.116
                    DC1_L2LEAF4:
                      hosts:
                        DC1-L2LEAF4A:
                          ansible_host: 192.168.200.119
                    DC1_L2LEAF5:
                      hosts:
                        DC1-L2LEAF5A:
                          ansible_host: 192.168.200.120
                        DC1-L2LEAF5B:
                          ansible_host: 192.168.200.121
                    TESTS:
                      hosts:
                        mgmt_interface_default:
                        mgmt_interface_fabric:
                        mgmt_interface_host:
                        mgmt_interface_platform:
                MH_LEAFS_TESTS:
                  # Connected to Spine1 Eth10-12
                  children:
                    MH_L3LEAF1:
                      hosts:
                        MH-LEAF1A:
                        MH-LEAF1B:
                    MH_L3LEAF2:
                      hosts:
                        MH-LEAF2A:
                MH_L2LEAFS_TESTS:
                  hosts:
                    MH-L2LEAF1A:
                MLAG_OSPF_TESTS:
                  children:
                    MLAG_OSPF_L3LEAF1:
                      hosts:
                        MLAG-OSPF-L3LEAF1A:
                        MLAG-OSPF-L3LEAF1B:
            DC1_TENANTS_NETWORKS:
              children:
                DC1_LEAFS:
                DC1_L2LEAFS:

            DC1_SERVERS:
              children:
                DC1_LEAFS:
                DC1_L2LEAFS:

            MH_TENANT_NETWORKS:
              children:
                MH_LEAFS_TESTS:
                MH_L2LEAFS_TESTS:

            MH_SERVERS:
              children:
                MH_LEAFS_TESTS:
                MH_L2LEAFS_TESTS:
