router_bgp:
  as: '65101'
  router_id: 192.168.255.21
  bgp_defaults:
  - maximum-paths 4 ecmp 4
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: '65101'
      next_hop_self: true
      description: CUSTOM-TEMPLATES-L3LEAF1B
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      send_community: all
      maximum_routes: 0
  address_family_ipv4:
    peer_groups:
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  neighbors:
    10.255.251.11:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: CUSTOM-TEMPLATES-L3LEAF1B
    172.31.255.20:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65001'
      description: CUSTOM-TEMPLATES-SPINE1_Ethernet1
    192.168.255.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: CUSTOM-TEMPLATES-SPINE1
      remote_as: '65001'
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.200.101/24
    gateway: 192.168.200.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
spanning_tree:
  no_spanning_tree_vlan: 4093-4094
vlans:
  4093:
    tenant: system
    name: LEAF_PEER_L3
    trunk_groups:
    - LEAF_PEER_L3
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
vlan_interfaces:
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    shutdown: false
    ip_address: 10.255.251.10/31
    mtu: 9000
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 10.255.252.10/31
    no_autostate: true
    mtu: 9000
port_channel_interfaces:
  Port-Channel3:
    description: TEST_CUSTOM_PREFIX_MLAG_PEER_CUSTOM-TEMPLATES-L3LEAF1B_Po3
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    trunk_groups:
    - LEAF_PEER_L3
    - MLAG
ethernet_interfaces:
  Ethernet3:
    peer: CUSTOM-TEMPLATES-L3LEAF1B
    peer_interface: Ethernet3
    peer_type: mlag_peer
    description: TEST_CUSTOM_PREFIX_MLAG_PEER_CUSTOM-TEMPLATES-L3LEAF1B_Ethernet3
    type: switched
    shutdown: false
    channel_group:
      id: 3
      mode: active
  Ethernet4:
    peer: CUSTOM-TEMPLATES-L3LEAF1B
    peer_interface: Ethernet4
    peer_type: mlag_peer
    description: TEST_CUSTOM_PREFIX_MLAG_PEER_CUSTOM-TEMPLATES-L3LEAF1B_Ethernet4
    type: switched
    shutdown: false
    channel_group:
      id: 3
      mode: active
  Ethernet1:
    peer: CUSTOM-TEMPLATES-SPINE1
    peer_interface: Ethernet1
    peer_type: spine
    description: TEST_CUSTOM_PREFIX_P2P_LINK_TO_CUSTOM-TEMPLATES-SPINE1_Ethernet1
    mtu: 9000
    type: routed
    shutdown: false
    ip_address: 172.31.255.21/31
mlag_configuration:
  domain_id: CUSTOM_TEMPLATES_L3LEAF1
  local_interface: Vlan4094
  peer_address: 10.255.252.11
  peer_link: Port-Channel3
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
route_maps:
  RM-MLAG-PEER-IN:
    sequence_numbers:
      10:
        type: permit
        set:
        - origin incomplete
        description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
loopback_interfaces:
  Loopback0:
    description: TEST_CUSTOM_PREFIX_EVPN_Overlay_Peering_L3LEAF
    shutdown: false
    ip_address: 192.168.255.21/32
  Loopback1:
    description: TEST_CUSTOM_PREFIX_VTEP_VXLAN_Tunnel_Source_L3LEAF
    shutdown: false
    ip_address: 192.168.254.21/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.255.0/24 eq 32
      20:
        action: permit 192.168.254.0/24 eq 32
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
vxlan_interface:
  Vxlan1:
    description: CUSTOM-TEMPLATES-L3LEAF1A_VTEP
    vxlan:
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
      udp_port: 4789
