download_url: https://galaxy.ansible.com/download/arista-avd-3.7.0.tar.gz
format_version: 1.0.0
name: avd
namespace: arista
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.7.0
version_url: https://galaxy.ansible.com/api/v2/collections/arista/avd/versions/3.7.0/
