---
collections:
  - name: community.general
    version: '*'
    source: https://galaxy.ansible.com
  - name: arista.avd
    version: '*'
    source: https://galaxy.ansible.com
#  - name: titom73.avd_tools
#   version: '*'
#    source: https://galaxy.ansible.com  